using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using MotionMouse.Connection;
using MotionMouse.Settings;
using System.Windows;
using Application = System.Windows.Application;
using System.Windows.Media;
using Brush = System.Windows.Media.Brush;
using Color = System.Windows.Media.Color;
using SolidColorBrush = System.Windows.Media.SolidColorBrush;

namespace MotionMouse.UI.ViewModels;

/// <summary>
/// ViewModel for MainWindow.
///
/// Exposes all state the main window needs as observable properties.
/// Subscribes to ConnectionManager events and translates them into
/// bindable properties that WPF can react to automatically.
///
/// Uses CommunityToolkit.Mvvm source generation:
///   [ObservableProperty] generates the property + backing field +
///   INotifyPropertyChanged calls automatically.
///   [RelayCommand] generates ICommand wrappers for methods.
///
/// All properties are updated on the UI thread — ConnectionManager
/// already marshals its events via Dispatcher.BeginInvoke().
/// </summary>
public sealed partial class MainViewModel : ObservableObject, IDisposable
{
    private readonly ConnectionManager  _connectionManager;
    private readonly SettingsRepository _settingsRepository;

    // -----------------------------------------------------------------------
    // Observable properties — auto-generated by [ObservableProperty]
    // -----------------------------------------------------------------------

    /// <summary>Primary status text shown large in the connection card.</summary>
    [ObservableProperty] private string _statusText = "Not Connected";

    /// <summary>Secondary status text — transport name or helper message.</summary>
    [ObservableProperty] private string _subStatusText = "Open Motion Mouse on your phone";

    /// <summary>Connection type label — "Wi-Fi" or "Bluetooth".</summary>
    [ObservableProperty] private string _connectionTypeName = "";

    /// <summary>Connected Android device name.</summary>
    [ObservableProperty] private string _deviceName = "";

    /// <summary>Battery level percentage (0-100).</summary>
    [ObservableProperty] private int _batteryLevel = 0;

    /// <summary>One-way latency in milliseconds.</summary>
    [ObservableProperty] private long _latencyMs = 0;

    /// <summary>Motion status description text.</summary>
    [ObservableProperty] private string _motionStatusText = "Active";

    /// <summary>Lock status label — "ACTIVE" or "LOCKED".</summary>
    [ObservableProperty] private string _lockStatusText = "ACTIVE";

    /// <summary>Background brush for the lock indicator pill.</summary>
    [ObservableProperty] private Brush _lockIndicatorBackground =
        new SolidColorBrush(Color.FromArgb(30, 0, 230, 118));

    /// <summary>Foreground brush for the lock indicator pill text.</summary>
    [ObservableProperty] private Brush _lockIndicatorForeground =
        new SolidColorBrush(Color.FromArgb(255, 0, 230, 118));

    /// <summary>True when a device is fully connected.</summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsDisconnected))]
    private bool _isConnected = false;

    /// <summary>True when listening for connections.</summary>
    [ObservableProperty] private bool _isListening = false;

    /// <summary>Inverse of IsConnected — used for visibility bindings.</summary>
    public bool IsDisconnected => !IsConnected;

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    public MainViewModel(
        ConnectionManager connectionManager,
        SettingsRepository settingsRepository)
    {
        _connectionManager  = connectionManager;
        _settingsRepository = settingsRepository;

        // Subscribe to connection events
        _connectionManager.StateChanged   += OnConnectionStateChanged;
        _connectionManager.StatusReceived += OnStatusReceived;
        _connectionManager.LatencyUpdated += OnLatencyUpdated;

        // Initialise to current state in case we're created after connect
        OnConnectionStateChanged(_connectionManager.CurrentState);
    }

    // -----------------------------------------------------------------------
    // Commands
    // -----------------------------------------------------------------------

    /// <summary>
    /// Disconnect the current session and return to listening.
    /// </summary>
    [RelayCommand]
    private async Task Disconnect()
    {
        await _connectionManager.DisconnectAsync();
    }

    /// <summary>
    /// Open the settings window.
    /// </summary>
    [RelayCommand]
    private void OpenSettings()
    {
        if (Application.Current is App app)
            app.ShowSettingsWindow();
    }

    // -----------------------------------------------------------------------
    // Event handlers
    // -----------------------------------------------------------------------

    private void OnConnectionStateChanged(ConnectionState state)
    {
        switch (state)
        {
            case ConnectionState.Connected:
                var client = _connectionManager.Client;
                IsConnected        = true;
                IsListening        = false;
                StatusText         = "Connected";
                SubStatusText      = $"via {client?.TransportName ?? ""}";
                ConnectionTypeName = client?.TransportName ?? "";
                DeviceName         = client?.DeviceName ?? "";
                MotionStatusText   = "Active";
                SetLockState(false);
                break;

            case ConnectionState.Listening:
                IsConnected        = false;
                IsListening        = true;
                StatusText         = "Searching…";
                SubStatusText      = "Waiting for Motion Mouse on your phone";
                ConnectionTypeName = "";
                DeviceName         = "";
                LatencyMs          = 0;
                BatteryLevel       = 0;
                break;

            case ConnectionState.Handshaking:
                IsConnected   = false;
                IsListening   = true;
                StatusText    = "Connecting…";
                SubStatusText = "Completing handshake";
                break;

            case ConnectionState.Idle:
                IsConnected        = false;
                IsListening        = false;
                StatusText         = "Not Connected";
                SubStatusText      = "Open Motion Mouse on your phone";
                ConnectionTypeName = "";
                break;
        }
    }

    private void OnStatusReceived(int batteryLevel, bool isLocked)
    {
        BatteryLevel = batteryLevel;
        SetLockState(isLocked);
    }

    private void OnLatencyUpdated(long latencyMs)
    {
        LatencyMs = latencyMs;
    }

    /// <summary>
    /// Update lock-related display properties.
    /// The lock indicator pill changes colour based on state.
    /// </summary>
    private void SetLockState(bool isLocked)
    {
        if (isLocked)
        {
            MotionStatusText        = "Locked";
            LockStatusText          = "LOCKED";
            LockIndicatorBackground = new SolidColorBrush(
                Color.FromArgb(30, 41, 121, 255));   // Blue tint
            LockIndicatorForeground = new SolidColorBrush(
                Color.FromArgb(255, 41, 121, 255));  // Blue text
        }
        else
        {
            MotionStatusText        = "Active";
            LockStatusText          = "ACTIVE";
            LockIndicatorBackground = new SolidColorBrush(
                Color.FromArgb(30, 0, 230, 118));    // Green tint
            LockIndicatorForeground = new SolidColorBrush(
                Color.FromArgb(255, 0, 230, 118));   // Green text
        }
    }

    // -----------------------------------------------------------------------
    // Cleanup
    // -----------------------------------------------------------------------

    public void Dispose()
    {
        _connectionManager.StateChanged   -= OnConnectionStateChanged;
        _connectionManager.StatusReceived -= OnStatusReceived;
        _connectionManager.LatencyUpdated -= OnLatencyUpdated;
    }
}
